library: /config/library.db
directory: /music
art_filename: albumart
import:
  write: yes
  copy: yes
  group_albums: yes
  duplicate_action: remove
  quiet: yes
  quiet_fallback: asis
  resume: yes
  incremental: yes
  from_scratch: yes
  languages: zh zh_CN zh_TW en jp
plugins: convert chroma bpm fetchart lyrics inline web
paths:
  default: $albumartist/$album/$title
  singleton: Singletons/$artist - $title
  comp: $album/$track $title
  albumtype:soundtrack: Soundtracks/$album/$title
convert:
  auto: yes
web:
  host: 0.0.0.0
  port: 26602
