library: /config/library.db
directory: /music
art_filename: albumart
import:
  write: yes
  copy: yes
  group_albums: yes
  duplicate_action: remove
  quiet: yes
  quiet_fallback: asis
  resume: yes
  incremental: yes
  from_scratch: yes
  languages: zh zh_CN zh_TW en jp
plugins: convert chroma discogs fetchart embedart lyrics inline web bpm
match:
  preferred:
    countries: ['CN', 'HK', 'TW', 'US', 'GB|UK']
    media: ['CD', 'Digital Media|File']
    original_year: yes
convert:
  auto: yes
chroma:
  auto: yes
musicbrainz:
  genres: yes
discogs:
  user_token: FQBmWfjUiooaXJSfwoJPlBbwKRIBMaZmSJdThQie
lyrics:
  sources: '*'
web:
  host: 0.0.0.0
  port: 26602
fetchart:
  sources:
    - filesystem
    - 'coverart: *'
    - itunes
    - amazon
    - albumart
    - fanarttv
    - wikipedia
