version: '3'
services:
  beets:
    image: yuezzzzzzzzzzz/beets:latest
    volumes:
      - $local_config_dir:/config
      - $local_output_dir:/music
      - $local_source_dir:/src
    command:
      - import
      - /src
